# Generated by Django 4.1.6 on 2023-02-17 02:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Match_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('auto_charging_station', models.IntegerField()),
                ('auto_upper', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('auto_upper_counts', models.IntegerField()),
                ('auto_middle', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('auto_middle_counts', models.IntegerField()),
                ('auto_lower', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('auto_lower_counts', models.IntegerField()),
                ('teleop_upper', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('teleop_upper_counts', models.IntegerField()),
                ('teleop_middle', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('teleop_middle_counts', models.IntegerField()),
                ('teleop_lower', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('teleop_lower_counts', models.IntegerField()),
                ('cone_transport', models.IntegerField()),
                ('cube_transport', models.IntegerField()),
                ('end_charging_station', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('driver_ranking', models.IntegerField()),
                ('defense_ranking', models.IntegerField()),
                ('comment', models.CharField(max_length=128)),
                ('scout_name', models.CharField(max_length=32)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_data', to='teams.teams')),
            ],
        ),
    ]
