# Generated by Django 4.2.9 on 2024-02-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='pit_scout_status',
            field=models.BooleanField(default=False),
        ),
    ]
