# Generated by Django 4.2.9 on 2024-02-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HumanPlayerMatch',
            new_name='Human_Player_Match',
        ),
    ]
