# Generated by Django 4.2.9 on 2024-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanPlayerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_number", models.IntegerField()),
                ("event", models.CharField(default="testing", max_length=16)),
                ("match_number", models.IntegerField()),
                ("human_player_timing", models.IntegerField(default=-1)),
                ("human_player_spotlit", models.IntegerField(default=-1)),
                ("strategist_name", models.CharField(default="", max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name="team_match_data",
            name="human_player_spotlit",
        ),
        migrations.RemoveField(
            model_name="team_match_data",
            name="human_player_timing",
        ),
        migrations.RemoveField(
            model_name="team_match_data",
            name="strategist_name",
        ),
    ]
