# Generated by Django 4.2.9 on 2024-01-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_additional_info_alter_teams_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
