# Generated by Django 4.2.9 on 2024-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_teams_robot_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_match_data',
            name='event',
            field=models.CharField(default='testing', max_length=16),
        ),
    ]
