# Generated by Django 4.2.9 on 2024-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_match_data_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='event',
            field=models.CharField(default='testing', max_length=16),
        ),
    ]
