databases:
  - name: scouting_backend
    databaseName: scouting_backend
    user: scouting_backend

services:
  - type: web
    name: scouting_backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn scouting_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scouting_backend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4